name: publish & deploy

on:
  push:
    tags:
      - "*"

jobs:
  publish_image:
    name: Build and push mal-cover image
    runs-on: ubuntu-latest
    outputs:
      img_tag: ${{ steps.tag.outputs.img_tag }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Remove 'v' from tag
        id: tag
        env:
          github_ref: ${{ github.ref }}
        run: |
          github_ref=${github_ref##*/}
          github_ref=${github_ref/v/}
          echo "IMG_TAG=${github_ref}" >> $GITHUB_ENV
          echo "img_tag=${github_ref}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Auth gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1
      - name: Setup docker
        run: |
          gcloud --quiet auth configure-docker
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./build/package/Dockerfile
          push: true
          tags: |
            rl404/mal-cover:latest
            rl404/mal-cover:${{ env.IMG_TAG }}
            ghcr.io/rl404/mal-cover:latest
            ghcr.io/rl404/mal-cover:${{ env.IMG_TAG }}
            ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/mal-cover:${{ env.IMG_TAG }}
  deploy:
    name: Deploy
    needs: publish_image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./deployment/terraform
    steps:
      - uses: actions/checkout@v4
      - name: Auth gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Setup Terraform Variables
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          gcp_project_id          = "${{ secrets.GCP_PROJECT_ID }}"
          gcp_region              = "${{ secrets.GCP_REGION }}"
          gcr_image_name          = "${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/mal-cover:${{ needs.publish_image.outputs.img_tag }}"
          cloud_run_name          = "${{ secrets.CLOUD_RUN_NAME }}"
          cloud_run_location      = "${{ secrets.CLOUD_RUN_LOCATION }}"
          mc_cache_dialect        = "${{ secrets.MC_CACHE_DIALECT }}"
          mc_cache_address        = "${{ secrets.MC_CACHE_ADDRESS }}"
          mc_cache_password       = "${{ secrets.MC_CACHE_PASSWORD }}"
          mc_cache_time           = "${{ secrets.MC_CACHE_TIME }}"
          mc_log_level            = "${{ secrets.MC_LOG_LEVEL }}"
          mc_log_json             = "${{ secrets.MC_LOG_JSON }}"
          mc_newrelic_license_key = "${{ secrets.MC_NEWRELIC_LICENSE_KEY }}"
          EOF
      - name: Init Terraform
        run: terraform init -backend-config "bucket=${{ secrets.GCS_BUCKET }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Format Terraform
        run: terraform fmt -check
      - name: Plan Terraform
        run: terraform plan -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Apply Terraform
        run: terraform apply -auto-approve -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
