name: publish & deploy

on :
  push:
    tags:
      - '*'

jobs:
  publish_image:
    name: Build and push mal-cover image
    runs-on: ubuntu-latest
    outputs:
      img_tag: ${{ steps.tag.outputs.img_tag }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Remove 'v' from tag
      id: tag
      env:
        github_ref: ${{ github.ref }}
      run : |
        github_ref=${github_ref##*/}
        github_ref=${github_ref/v/}
        echo "IMG_TAG=${github_ref}" >> $GITHUB_ENV
        echo "::set-output name=img_tag::${github_ref}"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          rl404/mal-cover:latest
          rl404/mal-cover:${{ env.IMG_TAG }}
          ghcr.io/rl404/mal-cover:latest
          ghcr.io/rl404/mal-cover:${{ env.IMG_TAG }}
  deploy:
    name: Deploy
    needs: publish_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auth gcloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
      - name: Deploy
        run: |
          gcloud run services update ${{ secrets.RUN_SERVICE_NAME }} --platform=managed --region=${{ secrets.RUN_REGION }} --quiet --image=rl404/mal-cover:${{ needs.publish_image.outputs.img_tag }}
